development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails_blog
  pool: 5
  username: root
  password: root

test:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails_blog
  pool: 5
  username: root
  password: root


production:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails_blog
  pool: 5
  username: root
  password: root
